FROM python:3.12

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libprotobuf-dev \
    protobuf-compiler \ 
    python3-dev

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

RUN export ARGOS_PACKAGES_DIR="/app/models"

RUN export ARGOS_DEVICE_TYPE="cpu"

COPY . .

CMD [ "python", "-m", "src.interfaces.grpc.server" ]