# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: argostranslate.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x14\x61rgostranslate.proto";\n\x07Request\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tfrom_lang\x18\x02 \x01(\t\x12\x0f\n\x07to_lang\x18\x03 \x01(\t"\x16\n\x06Result\x12\x0c\n\x04text\x18\x01 \x01(\t20\n\x0e\x41rgosTranslate\x12\x1e\n\ttranslate\x12\x08.Request\x1a\x07.Resultb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "argostranslate_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_REQUEST"]._serialized_start = 24
    _globals["_REQUEST"]._serialized_end = 83
    _globals["_RESULT"]._serialized_start = 85
    _globals["_RESULT"]._serialized_end = 107
    _globals["_ARGOSTRANSLATE"]._serialized_start = 109
    _globals["_ARGOSTRANSLATE"]._serialized_end = 157
# @@protoc_insertion_point(module_scope)
